# Generated by Django 3.2.8 on 2021-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceestimate',
            name='end_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceestimate',
            name='end_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceestimate',
            name='start_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceestimate',
            name='start_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timeestimate',
            name='start_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timeestimate',
            name='start_longitude',
            field=models.FloatField(),
        ),
    ]
